stages:
    - lint
    - test
    - publish
    - deploy
variables:
  BASE_IMAGE_URL: registry.gitlab.com/python-discord/projects/site/django-ci


.test-template: &test-template
    stage: test
    services:
        - postgres:11-alpine
    before_script:
        - python -m pip install -e .[test]
        - python manage.py migrate
    script:
        - python manage.py test
    tags:
        - docker
    variables:
        DATABASE_URL: postgres://django:supersecret@postgres/pysite
        POSTGRES_DB: pysite
        POSTGRES_PASSWORD: supersecret
        POSTGRES_USER: django
        SECRET_KEY: supersecret

lint-python:
    stage: lint
    image: python:3.7-alpine
    # Extract lint dependencies from the setup script.
    before_script:
        - >
            python -m pip install $(sed -n -e "/'lint': \[/,/]/p" setup.py | tail -n +2 | head -n -1 | cut -d"'" -f2)
    script:
        - flake8
    tags:
        - docker

lint-docker:
    stage: lint
    image: hadolint/hadolint:latest-debian
    script:
        - hadolint docker/**/**/**/Dockerfile
    tags:
        - docker

lint-markdown:
    stage: lint
    image: ruby:2.5-alpine
    before_script:
        - gem install mdl
    script:
        - mdl *.md **/*.md
    tags:
        - docker

test-3.7-alpine:
    <<: *test-template
    image: python:3.7-alpine
    before_script:
        - apk add gcc linux-headers musl-dev postgresql-dev
        - python -m pip install -e .[test]
        - python manage.py migrate
    script:
        - coverage run --branch manage.py test
        - coverage report
    artifacts:
        paths:
            - .coverage

test-3.6-alpine:
    <<: *test-template
    image: python:3.6-alpine
    before_script:
        - apk add gcc linux-headers musl-dev postgresql-dev
        - python -m pip install -e .[test]
        - python manage.py migrate

test-3.7-stretch:
    <<: *test-template
    image: python:3.7-stretch

test-3.6-stretch:
    <<: *test-template
    image: python:3.6-stretch

pages:
    image: python:3.7-alpine
    stage: publish
    dependencies:
        - test-3.7-alpine
    before_script:
        - pip install coverage
    script:
        - coverage html --directory=public
    artifacts:
        paths:
            - public
        expire_in: 30 days
    tags:
        - docker

push-django:
    image: docker:stable-git
    stage: publish
    script:
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker build -t pythondiscord/django:latest .
        - docker push pythondiscord/django:latest
    only:
        - master
        - django
    tags:
        - docker

deploy:
    stage: deploy
    image: alpine:latest
    before_script:
        - apk add --no-cache openssh-client
        - echo "$DJANGO_DEPLOY_SSH_PRIVATE_KEY" > id_ed25519
        - chmod 400 id_ed25519
    script:
        - ssh -i id_ed25519 -p 583 -o "StrictHostKeyChecking=no" pysite-deploy@jchri.st
    environment:
        name: Django staging
        url: https://pysite.jchri.st
    tags:
        - docker
    only:
        - master
        - django
